### ISSUE TITLE
Close and Reset button don't work

### ISSUE THREAD

**Issue by NiobeTM** [ranbuch/accessibility#83] opened 2024-10-17 06:26 UTC
Hey guys,

good morning and thank you for this great tool.

I have just imported the library (npm package) in my react app and since the menu is opened the close and reset buttons are not working.
The menu will only close only if I reload my page.

Any idea what I am doing wrong?

**Comment by ranbuch** [comment] 2024-10-19 22:16
Hi @NiobeTM 👋🏼 
Can you please create a [Stackblitz](https://stackblitz.com/) or something similar where I can reproduce the issue?

**Comment by natig4** [comment] 2024-11-03 20:16
Hey Ran,
I have the same issue, you can see it in my public repo: https://github.com/natig4/look-in-their-eyes.

Btw great solution, thank you very much for this, let me know if there is anything I can do to help.

**Comment by ranbuch** [comment] 2024-11-07 06:50
@natig4 Thank you for the update. According to what you wrote with the next.js version update it looks like the issue is not related to this repo. Do you agree or would you suggest otherwise?

**Comment by natig4** [comment] 2024-11-07 10:31
@ranbuch Yes, it wasn't related to this repo, according to what I saw you can close the issue.

thanks and have a great day,
Nati.

**Closed** 2024-11-08 16:33 UTC
